name: CI/CD

on:
  push:
  pull_request:

jobs:
  call-workflow-build:
    uses: ./.github/workflows/build.yaml
  
  call-workflow-lint:
    needs: [call-workflow-build]
    uses: ./.github/workflows/lint.yaml
  
  call-workflow-test:
    needs: [call-workflow-lint]
    uses: ./.github/workflows/test.yaml
  
  call-workflow-push:
    if: github.event_name == 'push'
    needs: [call-workflow-test]
    uses: ./.github/workflows/push.yaml
    secrets: inherit

  call-workflow-deploy:
    if: github.event_name == 'push'
    needs: [call-workflow-push]
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit

  call-workflow-health-check:
    if: github.event_name == 'push'
    needs: [call-workflow-deploy]
    uses: ./.github/workflows/health.yaml
    secrets: inherit