name: Push Docker Images

on:
    workflow_call:

jobs:
    image-build-and-push:
        name: Build and push Docker images
        runs-on: ubuntu-latest
        timeout-minutes: 30

        env:
            REGISTRY: "cr.selcloud.ru/finance-tracker"
            BACKEND_NAME: "finance-tracker-backend"
            FRONTEND_NAME: "finance-tracker-frontend"

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Registry
              run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY

            - name: Build and push backend image
              run: |
                  docker buildx build \
                    --no-cache \
                    --push \
                    --tag $REGISTRY/$BACKEND_NAME:latest \
                    --file Dockerfile \
                    .

            - name: Build and push frontend image
              run: |
                  TAG_NAME=$(echo $GITHUB_SHA | head -c7)
                  docker buildx build \
                    --no-cache \
                    --push \
                    --tag $REGISTRY/$FRONTEND_NAME:latest \
                    --file ./frontend/Dockerfile \
                    ./frontend
